import { lazy, Suspense, useEffect, useMemo, useState } from 'react';
import type { Tactics } from './campaign/contracts';
import { completeActiveMatch, createTournamentCampaign, fixtureForActive, groupStandings, openNextMatch, readTournamentCampaign, resetTournamentCampaign, teamFor, TOURNAMENT_TEAMS, type TournamentCampaign, writeTournamentCampaign } from './campaign/tournament';
import './your-world-cup.css';

const MatchExperience = lazy(() => import('./match/MatchExperience').then((module) => ({ default: module.MatchExperience })));
const groupForNation = (campaign: TournamentCampaign) => Object.entries(campaign.groups).find(([, teams]) => teams.includes(campaign.nation))?.[0] ?? 'A';
const stageLabel = (stage: TournamentCampaign['stage']) => stage === 'groups' ? 'Group stage' : stage.replaceAll('-', ' ');

function reducedMotion() { return typeof window.matchMedia === 'function' && window.matchMedia('(prefers-reduced-motion: reduce)').matches; }
function CampaignLabel() { return <p className="ywc-simulation-label">YOUR WORLD CUP · SIMULATED PERSONAL TOURNAMENT</p>; }

function Opening({ hasCampaign, onStart, onContinue }: { hasCampaign: boolean; onStart: () => void; onContinue: () => void }) {
  return <main className="ywc-prototype ywc-opening" data-screen="opening"><div className="ywc-print-noise" aria-hidden="true" /><section className="ywc-opening__copy"><CampaignLabel /><h1><span>Your</span><span>World Cup</span></h1><p className="ywc-marker-line">Choose a nation. Survive the draw. Write a fictional tournament story.</p><div className="ywc-opening__stickers" aria-hidden="true"><span>48 nations</span><span>12 groups</span><span>One trophy</span></div></section><div className="ywc-opening__actions"><button type="button" className="ywc-button ywc-button--primary" onClick={onStart}>Start new campaign <span aria-hidden="true">→</span></button>{hasCampaign ? <button type="button" className="ywc-button ywc-button--paper" onClick={onContinue}>Continue campaign <span aria-hidden="true">↗</span></button> : null}</div><div className="ywc-opening__terrace">Fictional draw · local campaign record · never official World Cup results</div></main>;
}

function NationSelect({ selected, onSelect, onBack }: { selected: string | null; onSelect: (nation: string) => void; onBack: () => void }) {
  return <main className="ywc-prototype ywc-nations" data-screen="nation"><header className="ywc-screen-head"><button type="button" className="ywc-back" onClick={onBack}>← Back</button><CampaignLabel /></header><section className="ywc-nations__intro"><p className="ywc-kicker">Sticker sheet · fictional campaign field</p><h1>Pick your <em>colors</em></h1><p>Every nation below is an owned, fictional campaign rating—not an official qualified field.</p></section><section className="ywc-sticker-sheet" aria-label="Choose a nation"><div className="ywc-sticker-grid ywc-sticker-grid--full">{TOURNAMENT_TEAMS.map((team) => <button type="button" key={team.id} className={`ywc-nation-sticker${selected === team.id ? ' is-selected' : ''}`} aria-pressed={selected === team.id} onClick={() => onSelect(team.id)}><span className="ywc-sticker-disc" style={{ background: team.color }}>{team.code}</span><strong>{team.name}</strong><span>Rating {team.rating}</span></button>)}</div></section></main>;
}

function Draw({ campaign, onEnter }: { campaign: TournamentCampaign; onEnter: () => void }) {
  const group = groupForNation(campaign); const teams = campaign.groups[group].map(teamFor);
  return <main className="ywc-prototype ywc-draw is-complete" data-screen="draw" data-draw-complete="true"><header className="ywc-screen-head ywc-screen-head--dark"><CampaignLabel /></header><section className="ywc-draw__stage"><article className="ywc-draw-poster"><p>United 26 · Personal draw</p><h1>Group <strong>{group}</strong></h1><div className="ywc-draw-grid">{teams.map((team) => <div className="ywc-draw-sticker" key={team.id}><b style={{ background: team.color }}>{team.code}</b><span>{team.name}</span></div>)}</div><p className="ywc-draw-marker">THE DRAW IS FICTIONAL. YOUR CAMPAIGN STARTS HERE.</p></article><div className="ywc-draw-footer"><p className="ywc-draw-status">Group {group} is on the wall.</p><button type="button" className="ywc-button ywc-button--marigold" onClick={onEnter}>Enter campaign <span aria-hidden="true">→</span></button></div></section></main>;
}

function GroupTable({ campaign }: { campaign: TournamentCampaign }) {
  const group = groupForNation(campaign); const table = groupStandings(campaign, group);
  return <section className="ywc-group-table" aria-label={`Group ${group} standings`}><div className="ywc-artifact-title"><span>Group {group}</span><b>PTS</b></div><div className="ywc-table-head"><span>Nation</span><span>PL</span><span>GD</span><span>PTS</span></div>{table.map((row) => { const team = teamFor(row.team); return <div className={`ywc-table-row${row.team === campaign.nation ? ' is-you' : ''}`} key={row.team}><span><i style={{ background: team.color }} />{team.name}</span><b>{row.played}</b><b>{row.goalDifference}</b><b>{row.points}</b></div>; })}<p className="ywc-table-scrawl">Tie-breakers: points · goal difference · goals scored · team code.</p></section>;
}

function Bracket({ campaign }: { campaign: TournamentCampaign }) {
  const fixtures = campaign.fixtures.filter((fixture) => fixture.stage !== 'groups');
  if (!fixtures.length) return <p className="ywc-bracket-empty">Round of 32 brackets print after all group matches are settled.</p>;
  return <section className="ywc-bracket" aria-label="Fictional knockout bracket">{fixtures.map((fixture) => <article className={`ywc-bracket-match${fixture.home === campaign.nation || fixture.away === campaign.nation ? ' is-you' : ''}`} key={fixture.id}><p>{fixture.stage.replaceAll('-', ' ')}</p><b>{teamFor(fixture.home).code} {fixture.played ? fixture.homeGoals : '–'} <span>v</span> {fixture.played ? fixture.awayGoals : '–'} {teamFor(fixture.away).code}</b>{fixture.homePenalties != null ? <small>{fixture.homePenalties}–{fixture.awayPenalties} pens</small> : null}</article>)}</section>;
}

function CampaignWall({ campaign, onNext, onNew }: { campaign: TournamentCampaign; onNext: () => void; onNew: () => void }) {
  const next = campaign.fixtures.find((fixture) => !fixture.played && (fixture.home === campaign.nation || fixture.away === campaign.nation));
  return <main className="ywc-prototype ywc-campaign" data-screen="campaign"><header className="ywc-campaign__header"><CampaignLabel /><p>{teamFor(campaign.nation).name} · campaign record</p><h1>The campaign wall</h1><span className="ywc-campaign-stamp">{stageLabel(campaign.stage)}</span></header><section className="ywc-wall"><div className="ywc-wall__table"><GroupTable campaign={campaign} /></div><article className="ywc-next-ticket"><p>{next ? stageLabel(next.stage) : stageLabel(campaign.stage)}</p>{next ? <><h2><span>{teamFor(next.home).code}</span><i>v</i><span>{teamFor(next.away).code}</span></h2><dl><div><dt>Fixture</dt><dd>{teamFor(next.home).name} v {teamFor(next.away).name}</dd></div><div><dt>Campaign</dt><dd>{campaign.history.length} result{campaign.history.length === 1 ? '' : 's'} pinned</dd></div></dl></> : <h2>{campaign.trophy ? 'Trophy on the wall' : campaign.eliminated ? 'Campaign complete' : 'Bracket printing'}</h2>}</article><aside className="ywc-wall-notes"><span className="ywc-note ywc-note--pink">fiction only<br />official truth untouched</span><span className="ywc-note ywc-note--gold">12 groups<br />32-team knockout</span></aside></section><Bracket campaign={campaign} /><section className="ywc-history" aria-label="Campaign history"><h2>Match ledger</h2>{campaign.history.length ? campaign.history.map((item, index) => <p key={`${item}-${index}`}>{item}</p>) : <p>No result yet. Three group matches stand between you and the knockouts.</p>}</section><div className="ywc-campaign__action">{next ? <button type="button" className="ywc-button ywc-button--pink" onClick={onNext}>Prepare {teamFor(next.home).code} v {teamFor(next.away).code} <span aria-hidden="true">→</span></button> : <button type="button" className="ywc-button ywc-button--paper" onClick={onNew}>New campaign <span aria-hidden="true">↺</span></button>}</div></main>;
}

function TacticsBoard({ campaign, onChange, onKickoff, onBack }: { campaign: TournamentCampaign; onChange: (value: Tactics) => void; onKickoff: () => void; onBack: () => void }) {
  const fixture = fixtureForActive(campaign); if (!fixture) return null;
  const rows: readonly [keyof Tactics, readonly string[], string][] = [['shape', ['4-3-3-wide', '4-2-3-1-control'], 'Shape'], ['press', ['patient', 'balanced', 'aggressive'], 'Press'], ['finalThird', ['wings', 'number-10', 'direct-runners'], 'Final-third plan']];
  return <main className="ywc-prototype ywc-tactics" data-screen="tactics"><header className="ywc-screen-head"><button type="button" className="ywc-back" onClick={onBack}>← Wall</button><CampaignLabel /></header><section className="ywc-clipboard"><p className="ywc-kicker">Coach clipboard · fictional campaign</p><h1>Make the <em>plan</em></h1><div className="ywc-tactics-pitch" aria-label={`Formation ${campaign.tactics.shape}`}><b>4</b><b>3</b><b>3</b><span>Canvas match presentation uses this shape, compactness, press and running lanes.</span></div>{rows.map(([key, values, label]) => <fieldset className="ywc-choice" key={key}><legend>{label}</legend>{values.map((value) => <button type="button" key={value} className={campaign.tactics[key] === value ? 'is-selected' : ''} aria-pressed={campaign.tactics[key] === value} onClick={() => onChange({ ...campaign.tactics, [key]: value } as Tactics)}>{value.replaceAll('-', ' ')}</button>)}</fieldset>)}<p className="ywc-marker-note">{teamFor(fixture.home).name} v {teamFor(fixture.away).name} · {stageLabel(fixture.stage)}</p><button type="button" className="ywc-button ywc-button--pink" onClick={onKickoff}>Kick off <span aria-hidden="true">→</span></button></section></main>;
}

function Result({ campaign, onWall, onNew }: { campaign: TournamentCampaign; onWall: () => void; onNew: () => void }) {
  const latest = campaign.history.at(-1); const title = campaign.trophy ? 'CHAMPIONS OF YOUR WORLD CUP' : campaign.eliminated ? 'THE WALL HOLDS THE STORY' : 'RESULT PINNED';
  return <main className={`ywc-prototype ywc-full-time${campaign.trophy ? ' is-positive' : ''}`} data-screen="result"><article className="ywc-result-artifact"><CampaignLabel /><h1>{title}</h1><div className="ywc-result-score">{latest ?? 'Campaign result'}</div><strong>{campaign.trophy ? 'THE TROPHY IS YOURS. THIS IS A FICTIONAL PERSONAL CAMPAIGN.' : campaign.eliminated ? 'ELIMINATION IS FINAL. START A NEW CAMPAIGN WHEN YOU ARE READY.' : 'THE LEDGER, GROUP TABLES, AND BRACKET NOW AGREE.'}</strong></article>{campaign.trophy || campaign.eliminated ? <button type="button" className="ywc-button ywc-button--paper" onClick={onNew}>New campaign <span aria-hidden="true">↺</span></button> : <button type="button" className="ywc-button ywc-button--paper" onClick={onWall}>Return to wall <span aria-hidden="true">→</span></button>}</main>;
}

export function YourWorldCupPrototype() {
  const initial = useMemo(() => readTournamentCampaign(window.localStorage), []); const [campaign, setCampaign] = useState<TournamentCampaign | null>(initial); const [selecting, setSelecting] = useState(false); const motion = useMemo(reducedMotion, []);
  useEffect(() => { document.title = 'Your World Cup — United 26'; }, []);
  const save = (next: TournamentCampaign) => { writeTournamentCampaign(window.localStorage, next); setCampaign(next); };
  const begin = (nation: string) => { const next = { ...createTournamentCampaign(26062026 + (TOURNAMENT_TEAMS.findIndex((team) => team.id === nation) * 97), nation), screen: 'draw' as const }; save(next); setSelecting(false); };
  const newCampaign = () => { resetTournamentCampaign(window.localStorage); setCampaign(null); setSelecting(false); };
  if (!campaign && !selecting) return <Opening hasCampaign={false} onStart={() => setSelecting(true)} onContinue={() => {}} />;
  if (selecting || campaign?.screen === 'nation') return <NationSelect selected={campaign?.nation ?? null} onSelect={begin} onBack={() => setSelecting(false)} />;
  if (!campaign) return null;
  if (campaign.screen === 'opening') return <Opening hasCampaign onStart={() => setSelecting(true)} onContinue={() => save({ ...campaign, screen: 'wall' })} />;
  if (campaign.screen === 'draw') return <Draw campaign={campaign} onEnter={() => save({ ...campaign, screen: 'wall' })} />;
  if (campaign.screen === 'tactics') return <TacticsBoard campaign={campaign} onChange={(tactics) => save({ ...campaign, tactics })} onKickoff={() => save({ ...campaign, screen: 'match' })} onBack={() => save({ ...campaign, screen: 'wall', activeFixtureId: null })} />;
  if (campaign.screen === 'match') { const fixture = fixtureForActive(campaign); return fixture ? <Suspense fallback={<main className="ywc-prototype ywc-match-loading" role="status">Preparing Canvas match…</main>}><MatchExperience campaign={campaign} fixture={fixture} reducedMotion={motion} onBack={() => save({ ...campaign, screen: 'tactics' })} onComplete={(score) => save(completeActiveMatch(campaign, score))} /></Suspense> : <CampaignWall campaign={campaign} onNext={() => save(openNextMatch(campaign))} onNew={newCampaign} />; }
  if (campaign.screen === 'result') return <Result campaign={campaign} onWall={() => save({ ...campaign, screen: 'wall' })} onNew={newCampaign} />;
  return <CampaignWall campaign={campaign} onNext={() => save(openNextMatch(campaign))} onNew={newCampaign} />;
}
