import type { MomentOutcome, Tactics } from '../campaign/contracts';
import { campaignFixture } from '../campaign/match-data';

export type Point = Readonly<{ x: number; y: number }>;
export type MatchPlayer = Readonly<{ id: string; number: number; shortLabel: string; displayName: string; role: 'goalkeeper' | 'defender' | 'midfielder' | 'forward'; side?: 'left' | 'center' | 'right' }>;
export type MatchTeam = Readonly<{ id: string; name: string; shortName: string; colors: Readonly<{ primary: string; secondary: string; goalkeeper: string }>; direction: 'north' | 'south'; strengths: Readonly<{ attack: number; midfield: number; defense: number; goalkeeper: number; pace: number; discipline: number }>; lineup: readonly MatchPlayer[] }>;
export type TeamId = string;
export type SimulatedPlayerState = Readonly<{ id: string; teamId: TeamId; number: number; shortLabel: string; role: MatchPlayer['role']; position: Point; facing: 'up' | 'down'; active: boolean }>;
export type MatchAction = Readonly<{ type: 'pass' | 'carry' | 'turnover' | 'tackle' | 'foul' | 'corner' | 'shot' | 'save' | 'goal' | 'substitution' | 'phase' | 'pivotal-entry'; actor?: string; target?: string; teamId?: TeamId; keeper?: string; zone?: 'left' | 'center' | 'right'; phase?: 'buildup' | 'press' | 'transition' | 'final-third' | 'halftime' | 'full-time' }>;
export type PlannedMatchEvent = Readonly<{ id: string; minute: number; teamId: TeamId; action: MatchAction; possessionAfter: TeamId; start: Point; end: Point; scoreAfter: Readonly<{ home: number; away: number }> }>;
export type MatchPlan = Readonly<{ version: 1; fixtureId: string; seed: number; homeTeamId: TeamId; awayTeamId: TeamId; tactics: Tactics; pivotalMinute: number; pivotalTeamId: TeamId; events: readonly PlannedMatchEvent[]; baselineResultWithoutMoment: Readonly<{ home: number; away: number }> }>;
export type MatchFrame = Readonly<{ tick: number; minute: number; eventIndex: number; eventProgress: number; score: Readonly<{ home: number; away: number }>; possessionTeamId: TeamId; ball: Point; ballOwnerId: string | null; players: readonly SimulatedPlayerState[]; action: MatchAction | null; momentumContext: string; meaningful: boolean }>;
export type MatchInput = Readonly<{ fixtureId: string; campaignSeed: number; replaySalt?: string; home: MatchTeam; away: MatchTeam; tactics: Tactics }>;

const clamp = (value: number, min = 3, max = 97) => Math.max(min, Math.min(max, value));
const lerp = (a: number, b: number, n: number) => a + ((b - a) * n);
const hash = (text: string) => [...text].reduce((value, character) => ((value * 33) + character.charCodeAt(0)) >>> 0, 5381);
const random = (seed: number) => { let value = seed >>> 0; return () => { value += 0x6D2B79F5; let t = value; t = Math.imul(t ^ (t >>> 15), t | 1); t ^= t + Math.imul(t ^ (t >>> 7), t | 61); return ((t ^ (t >>> 14)) >>> 0) / 4294967296; }; };
const derivedSeed = (input: MatchInput) => hash(`${input.campaignSeed}:${input.fixtureId}:${input.home.id}:${input.away.id}:${input.tactics.shape}:${input.tactics.press}:${input.tactics.finalThird}:${input.replaySalt ?? 'v1'}`);
const score = (events: readonly PlannedMatchEvent[], index: number) => index < 0 ? { home: 0, away: 0 } : events[index].scoreAfter;
const attackingY = (team: MatchTeam) => team.direction === 'south' ? 4 : 96;

function anchor(player: MatchPlayer, team: MatchTeam, tactics: Tactics) {
  const direction = team.direction === 'south' ? 1 : -1;
  const roleY = player.role === 'goalkeeper' ? 7 : player.role === 'defender' ? 23 : player.role === 'midfielder' ? 48 : 70;
  const y = team.direction === 'south' ? 100 - roleY : roleY;
  const side = player.side === 'left' ? 20 : player.side === 'right' ? 80 : 50;
  const width = tactics.shape === '4-3-3-wide' && player.role === 'forward' ? (player.side === 'left' ? 12 : player.side === 'right' ? 88 : 50) : side;
  return { x: width, y: clamp(y + (player.role === 'midfielder' ? direction * (tactics.press === 'aggressive' ? 6 : tactics.press === 'patient' ? -3 : 0) : 0)) };
}

function statePlayers(input: MatchInput, possession: TeamId, actor: string | null, eventProgress: number, action: MatchAction | null) {
  return [input.home, input.away].flatMap((team) => team.lineup.map((player) => {
    const base = anchor(player, team, input.tactics); const forward = team.id === possession ? (team.direction === 'south' ? -6 : 6) : (team.direction === 'south' ? 3 : -3);
    const tacticalX = input.tactics.finalThird === 'wings' && player.role === 'forward' && player.side ? (player.side === 'left' ? -5 : player.side === 'right' ? 5 : 0) : input.tactics.finalThird === 'number-10' && player.role === 'midfielder' ? (50 - base.x) * .15 : 0;
    const moving = action && (action.type === 'pass' || action.type === 'carry' || action.type === 'shot') && (player.id === action.actor || player.id === action.target);
    const nudge = moving ? eventProgress * 8 : 0;
    return Object.freeze({ id: player.id, teamId: team.id, number: player.number, shortLabel: player.shortLabel, role: player.role, position: Object.freeze({ x: clamp(base.x + tacticalX + (player.id === action?.target ? (team.direction === 'south' ? -nudge : nudge) : 0)), y: clamp(base.y + forward + (player.id === action?.actor ? (team.direction === 'south' ? -nudge : nudge) : 0)) }), facing: team.direction === 'south' ? 'up' : 'down', active: player.id === actor });
  }));
}

function candidate(team: MatchTeam, role: MatchPlayer['role'] | 'any', rng: () => number) { const choices = team.lineup.filter((player) => role === 'any' || player.role === role); return choices[Math.floor(rng() * choices.length)] ?? team.lineup[0]; }
function commentary(event: PlannedMatchEvent, home: MatchTeam, away: MatchTeam) { const team = event.teamId === home.id ? home : away; const opponent = event.teamId === home.id ? away : home; switch (event.action.type) { case 'pass': return `${team.name} connect through the ${event.action.zone === 'left' || event.action.zone === 'right' ? 'wide channel' : 'central lane'}.`; case 'carry': return `${team.name} carry into space.`; case 'turnover': case 'tackle': return `${team.name} win it and turn play around.`; case 'shot': return `${team.name} open a shooting lane.`; case 'save': return `${event.action.keeper ? `${team.name}'s keeper` : opponent.name} makes the stop.`; case 'goal': return `${team.name} score after the ball reaches the net.`; case 'corner': return `${team.name} force a dangerous restart.`; case 'substitution': return `${team.name} freshen the shape.`; case 'pivotal-entry': return `${team.name} find a late opening. The next move is yours.`; case 'phase': return event.action.phase === 'halftime' ? 'Half-time. The match remains in balance.' : event.action.phase === 'full-time' ? 'Full time. The event ledger is complete.' : `The match shifts into ${event.action.phase}.`; default: return `${team.name} keep the match moving.`; } }

export function createMatchPlan(input: MatchInput): MatchPlan {
  const seed = derivedSeed(input); const rng = random(seed); const events: PlannedMatchEvent[] = []; let possession = rng() > .5 ? input.home.id : input.away.id; let homeGoals = 0; let awayGoals = 0;
  const strength = (team: MatchTeam, opponent: MatchTeam) => (team.strengths.attack + team.strengths.midfield + team.strengths.pace - opponent.strengths.defense - opponent.strengths.goalkeeper) / 100;
  const add = (minute: number, team: MatchTeam, action: MatchAction, next = team.id) => { if (action.type === 'goal') team.id === input.home.id ? homeGoals++ : awayGoals++; const actor = action.actor ? team.lineup.find((p) => p.id === action.actor) : undefined; const start = actor ? anchor(actor, team, input.tactics) : { x: 50, y: 50 }; const end = action.type === 'goal' || action.type === 'save' || action.type === 'shot' ? { x: action.zone === 'left' ? 32 : action.zone === 'right' ? 68 : 50, y: attackingY(team) } : { x: clamp(start.x + (team.direction === 'south' ? (action.zone === 'left' ? -16 : action.zone === 'right' ? 16 : 0) : (action.zone === 'left' ? -16 : action.zone === 'right' ? 16 : 0))), y: clamp(start.y + (team.direction === 'south' ? -15 : 15)) }; events.push(Object.freeze({ id: `${events.length}:${minute}:${action.type}`, minute, teamId: team.id, action: Object.freeze(action), possessionAfter: next, start: Object.freeze(start), end: Object.freeze(end), scoreAfter: Object.freeze({ home: homeGoals, away: awayGoals }) })); possession = next; };
  add(0, input.home, { type: 'phase', phase: 'buildup', teamId: input.home.id }, input.home.id);
  const pivotalMinute = 62 + Math.floor(rng() * 23); const minutes = Array.from({ length: 15 }, (_, index) => 4 + Math.floor(index * 84 / 15) + Math.floor(rng() * 3)).filter((minute) => minute !== pivotalMinute && minute !== 45).sort((a, b) => a - b);
  for (const minute of minutes) { const team = possession === input.home.id ? input.home : input.away; const opponent = team.id === input.home.id ? input.away : input.home; const volatility = input.tactics.press === 'aggressive' ? .26 : input.tactics.press === 'patient' ? .1 : .18; const attackBias = strength(team, opponent) + (input.tactics.finalThird === 'direct-runners' ? .08 : 0) + (input.tactics.press === 'aggressive' && minute < 55 ? .06 : 0) - (input.tactics.press === 'aggressive' && minute > 70 ? .11 : 0); const roll = rng(); const zone: 'left' | 'center' | 'right' = input.tactics.finalThird === 'wings' ? (rng() > .5 ? 'left' : 'right') : input.tactics.finalThird === 'number-10' ? 'center' : (rng() > .5 ? 'right' : 'left'); if (minute === 45) continue; if (roll < .22 + volatility) { const winner = opponent; add(minute, winner, { type: roll < .12 ? 'tackle' : 'turnover', actor: candidate(winner, 'midfielder', rng).id, teamId: winner.id }, winner.id); } else if (roll < .5) { const from = candidate(team, rng() > .5 ? 'midfielder' : 'defender', rng); const to = candidate(team, rng() > .5 ? 'forward' : 'midfielder', rng); add(minute, team, { type: 'pass', actor: from.id, target: to.id, zone, teamId: team.id }, team.id); } else if (roll < .67) add(minute, team, { type: 'carry', actor: candidate(team, 'forward', rng).id, zone, teamId: team.id }, team.id); else { const shooter = candidate(team, 'forward', rng); const chance = .35 + attackBias + (input.tactics.finalThird === 'direct-runners' ? .06 : 0) - (minute > 72 && input.tactics.press === 'aggressive' ? .08 : 0); add(minute, team, { type: 'shot', actor: shooter.id, zone, teamId: team.id }, team.id); if (rng() < chance) add(minute, team, { type: 'goal', actor: shooter.id, zone, teamId: team.id }, opponent.id); else add(minute, opponent, { type: 'save', keeper: candidate(opponent, 'goalkeeper', rng).id, zone, teamId: opponent.id }, opponent.id); }
  }
  add(45, input.home, { type: 'phase', phase: 'halftime', teamId: input.home.id }, possession); const pivotalTeam = homeGoals === awayGoals || homeGoals < awayGoals ? input.home : (possession === input.home.id ? input.home : input.away); add(pivotalMinute, pivotalTeam, { type: 'pivotal-entry', actor: candidate(pivotalTeam, 'midfielder', rng).id, teamId: pivotalTeam.id }, pivotalTeam.id); add(90, input.home, { type: 'phase', phase: 'full-time', teamId: input.home.id }, possession); events.sort((a, b) => a.minute - b.minute);
  const ordered = events.sort((a, b) => a.minute - b.minute); let ledgerHome = 0; let ledgerAway = 0; const coherent = ordered.map((event) => { if (event.action.type === 'goal') event.teamId === input.home.id ? ledgerHome++ : ledgerAway++; return Object.freeze({ ...event, scoreAfter: Object.freeze({ home: ledgerHome, away: ledgerAway }) }); });
  return Object.freeze({ version: 1, fixtureId: input.fixtureId, seed, homeTeamId: input.home.id, awayTeamId: input.away.id, tactics: input.tactics, pivotalMinute, pivotalTeamId: pivotalTeam.id, events: Object.freeze(coherent), baselineResultWithoutMoment: Object.freeze({ home: ledgerHome, away: ledgerAway }) });
}

export function injectPivotalOutcome(plan: MatchPlan, input: MatchInput, outcome: MomentOutcome | null): MatchPlan {
  if (!outcome) return plan; const pivotalIndex = plan.events.findIndex((event) => event.action.type === 'pivotal-entry'); if (pivotalIndex < 0) return plan; const team = plan.pivotalTeamId === input.home.id ? input.home : input.away; const opponent = team.id === input.home.id ? input.away : input.home; const rng = random(hash(`${plan.seed}:${outcome}:future`)); let home = plan.events[pivotalIndex].scoreAfter.home; let away = plan.events[pivotalIndex].scoreAfter.away; const before = plan.events.slice(0, pivotalIndex + 1); const after: PlannedMatchEvent[] = []; const add = (minute: number, owner: MatchTeam, action: MatchAction, possessionAfter: TeamId) => { if (action.type === 'goal') owner.id === input.home.id ? home++ : away++; const actor = action.actor ? owner.lineup.find((p) => p.id === action.actor) : undefined; const start = actor ? anchor(actor, owner, input.tactics) : { x: 50, y: 50 }; const end = action.type === 'goal' || action.type === 'save' || action.type === 'shot' ? { x: action.zone === 'left' ? 32 : action.zone === 'right' ? 68 : 50, y: attackingY(owner) } : start; after.push(Object.freeze({ id: `pivot:${after.length}:${minute}:${action.type}`, minute, teamId: owner.id, action: Object.freeze(action), possessionAfter, start: Object.freeze(start), end: Object.freeze(end), scoreAfter: Object.freeze({ home, away }) })); };
  if (outcome === 'goal') add(plan.pivotalMinute, team, { type: 'goal', actor: candidate(team, 'forward', rng).id, zone: rng() > .5 ? 'left' : 'right', teamId: team.id }, opponent.id); else add(plan.pivotalMinute, opponent, { type: outcome === 'interception' ? 'turnover' : 'save', actor: candidate(opponent, 'defender', rng).id, keeper: candidate(opponent, 'goalkeeper', rng).id, teamId: opponent.id }, opponent.id);
  for (let minute = plan.pivotalMinute + 4; minute < 90; minute += 4 + Math.floor(rng() * 4)) { const owner = rng() < .5 ? team : opponent; const other = owner.id === team.id ? opponent : team; const shoot = rng() < .42 + ((owner.strengths.attack - other.strengths.defense) / 200); if (shoot) { const shooter = candidate(owner, 'forward', rng); const goal = rng() < .24 + ((owner.strengths.attack - other.strengths.goalkeeper) / 220); add(minute, owner, { type: 'shot', actor: shooter.id, zone: rng() > .5 ? 'left' : 'right', teamId: owner.id }, owner.id); add(minute, goal ? owner : other, goal ? { type: 'goal', actor: shooter.id, teamId: owner.id } : { type: 'save', keeper: candidate(other, 'goalkeeper', rng).id, teamId: other.id }, goal ? other.id : other.id); } else add(minute, owner, { type: 'pass', actor: candidate(owner, 'midfielder', rng).id, target: candidate(owner, 'forward', rng).id, teamId: owner.id }, owner.id); }
  add(90, input.home, { type: 'phase', phase: 'full-time', teamId: input.home.id }, home >= away ? input.home.id : input.away.id);
  return Object.freeze({ ...plan, events: Object.freeze([...before.filter((event) => !(event.action.type === 'phase' && event.action.phase === 'full-time')), ...after]), baselineResultWithoutMoment: Object.freeze({ home, away }) });
}

export function buildPresentationFrames(plan: MatchPlan, input: MatchInput): readonly MatchFrame[] { const frames: MatchFrame[] = []; let priorScore = { home: 0, away: 0 }; plan.events.forEach((event, eventIndex) => { const steps = event.action.type === 'pass' || event.action.type === 'shot' || event.action.type === 'goal' || event.action.type === 'save' ? 7 : event.action.type === 'pivotal-entry' ? 3 : 4; for (let step = 0; step < steps; step++) { const progress = step / (steps - 1); const actor = event.action.actor ?? null; const players = statePlayers(input, event.teamId, actor, progress, event.action); const ball = event.action.type === 'pass' || event.action.type === 'shot' || event.action.type === 'goal' || event.action.type === 'save' ? { x: lerp(event.start.x, event.end.x, progress), y: lerp(event.start.y, event.end.y, progress) } : (actor ? players.find((player) => player.id === actor)?.position ?? event.start : event.start); const applyScore = event.action.type === 'goal' && progress < 1 ? priorScore : event.scoreAfter; frames.push(Object.freeze({ tick: frames.length, minute: event.minute, eventIndex, eventProgress: progress, score: Object.freeze(applyScore), possessionTeamId: event.possessionAfter, ball: Object.freeze(ball), ballOwnerId: (event.action.type === 'pass' || event.action.type === 'shot' || event.action.type === 'goal' || event.action.type === 'save') && progress < 1 ? actor : actor, players: Object.freeze(players), action: event.action, momentumContext: commentary(event, input.home, input.away), meaningful: step === 0 })); } priorScore = event.scoreAfter; }); return Object.freeze(frames); }

export function nextMeaningfulTick(frames: readonly MatchFrame[], currentTick: number) { return frames.find((frame) => frame.tick > currentTick && frame.meaningful)?.tick ?? frames.length - 1; }
export function planForCampaign(seed: number, tactics: Tactics, home: MatchTeam, away: MatchTeam) { return createMatchPlan({ fixtureId: `${home.id}-${away.id}`, campaignSeed: seed, home, away, tactics }); }
export function buildMatchFrames(seed: number, tactics: Tactics, outcome: MomentOutcome | null): readonly MatchFrame[] { const input = { fixtureId: campaignFixture.id, campaignSeed: seed, home: campaignFixture.home, away: campaignFixture.away, tactics } as const; return buildPresentationFrames(injectPivotalOutcome(createMatchPlan(input), input, outcome), input); }
export function finalScore(seed: number, tactics: Tactics, outcome: MomentOutcome) { const frames = buildMatchFrames(seed, tactics, outcome); return frames[frames.length - 1].score; }
